apiVersion: v1
kind: Pod
metadata:
  name: cpu-test
spec:
  containers:
  - name: cpu-test
    image: busybox
    command: ["sleep","3600"]
    resources:
      requests:
        cpu: "2"
      limits:
        cpu: "2"
