# n8n – prod overlay (namespace: n8n-prod, replace image with prod tag)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n-prod

resources:
  - namespace.yaml
  - ../../base

# Replace n8n image for prod
images:
  - name: n8nio/n8n
    newName: 392746353565.dkr.ecr.us-east-1.amazonaws.com/n8n-images
    newTag: "fcc_14"

replicas:
  - name: n8n-worker
    count: 3
  # Or your ECR: newName: 392746353565.dkr.ecr.us-east-1.amazonaws.com/n8n-images

